### ISSUE TITLE
Config data has been removed without interference from me in kiwi

### ISSUE THREAD

**Issue by BahrawiElimi** [K1DV5/extreme#2]
I don't know why I really didn't do anything.
I went back to default.

**Comment by K1DV5** [comment]
Did you install a new version of Kiwi?

**Comment by BahrawiElimi** [comment]
Yes latest version of kiwi 107.0.5304.75
With ‏‪Extreme 2.1.0

**Comment by K1DV5** [comment]
I suspect that's an issue with Kiwi, because extreme doesn't do anything fancy when the browser updates.

**Comment by BahrawiElimi** [comment]
Close.
This problem did not recur, and I do not know what was the reason for that
